### ISSUE TITLE
SVT-AV1 Feature tests

### ISSUE THREAD

**Issue by Cidana-Developers** [Cidana-Developers/UnitTests-Task-manager#33]
1. add non of multiple 64 test vectors to test incomplete sb test and border test (refer borders_test.cc).
2. based on dummy test cases, add maximum resolution and smaller resolution, like only 64x64 (refer to frame_size_tests.cc)
3. Tile: please refer to tile_independent_test.cc in libaom/test
4. Segment: Not supported
5. Active Map: Not Supported yet
6. AltRef: already tested; maybe it can be improved by refering to arf_freq_test.cc.
7. Scalability: Not Supported yet.
8. SceneChange: create a yuv file which contain the scene change, and verify the conformance test and check the I frame position

**Comment by Cidana-Emma** [comment]
done
