### ISSUE TITLE
Stage4 Unit tests

### ISSUE THREAD

**Issue by Cidana-Developers** [Cidana-Developers/UnitTests-Task-manager#34]
# Unit Test
1. CDEF Test
  - compute_cdef_dist
  - copy_rect8_8bit_to_16bit
  - cdef_find_dir_avx2 
  - cdef_filter_block_avx2
2. Restoration Test
  - apply_self_guided_restoration
  - compute_stats
  - wiener
  - av1_wiener_convolve_add_src_avx2
  - projection
  - av1_selfguided_restoration
3. Film Grain Test
  - aom_wiener_denoise_2d
4. Deblocking Test
  - aom_highbd_lpf_{vertical, horizontal)_sse2
# E2E Tests
## E2E Tests
  1. add RandomSource to test different resolution (non multiple of 64 wide, 64 wide, big resolution)
  2. add Configurable encoding options;
  4. tile independent test
  5. loop test: long-time test;
  7. scene change:
  8. border test:
  9. test vector: {422, 444, 400} + 8bit/10bit profile

**Comment by Cidana-Emma** [comment]
tests for stage 4 have been added, so close this issue
