### ISSUE TITLE
Summary of SVT-AV1 Unit Test Projects

### ISSUE THREAD

**Issue by Cidana-Developers** [Cidana-Developers/UnitTests-Task-manager#36]
# Summary Of SVT-AV1 Unit Test Projects
## Some modules are not mentioned in Contract
  1. Picture Operation SSE2
  2. Denoise Operation
  3. Pack and Unpack operations
  4. super resolution: av1_highbd_convolve_horiz_rs_sse4_1
  5. picture analysis
  6. others, should check the assembly code in SVT-AV1 thoroughly.

### Stage2
  1. Recur-filter intra
  2. Palatte mode
  3. others?

### Stage 3
  1. wedge mode, including WedgeUtil
  2. blend: blend_a64_mask_1d.test, blend_a64_mask.test
  3. compound avg: comp_avg_pred_test.cc
  4. compound mask: comp_mask_variance_test.cc
  5. mask sad:
  6. mask variance:
  7. others?

## Mentioned in Contract and implemented in SVT-AV1, no unit test
  1. aom sad functions
  2. 

# Summary of SVT-AV1 End to End test
## Completed:
  1. Support conformance test by comparing recon yuv and decoded yuv
  2. Support configurable test vectors and encoding options
  3. Support verifying the encoding options by analysing the bitstream.
  4. Support E2E test and API test
  5. Support run the encoding in another process.
  6. Support coding options:
    1. rate control mode: datarate test
    2. warp mode
  7. Support feature test:
    1. simulated qp file;
    2. 
## TODO:
  1. Regression test
  2. data size test
  3. tile independent test
  4. frame size test
  5. scene change;
  6. border test: low resolution with high qp or low qp with high resulution;

**Comment by Cidana-Emma** [comment]
done
