### ISSUE TITLE
E2E test failed case verification

### ISSUE THREAD

**Issue by edmond-zhu** [Cidana-Developers/UnitTests-Task-manager#39]
### End2End test, total: 59 tests, 4 tests failed as the following:
	1. ConformanceDeathTest.DefaultSettingTest/IntraPeriodTest2
	2. ConformanceDeathTest.DefaultSettingTest/LookAheadTest
	3. ConformanceDeathTest.DefaultSettingTest/SpeedControlTest1
	4. CodingOptionTest.CheckEncOptionsUsingBitstream/IntraPeriodTest1
	The failure of Speed Control test has been reported in Issue#368

**Comment by Cidana-Emma** [comment]
Verification done.
End2End failures have been reported to SVT-AV1 repo, so close this issue
