### ISSUE TITLE
Mismatch issue found in avc style mcp unit test

### ISSUE THREAD

**Issue by Cidana-Developers** [Cidana-Developers/UnitTests-Task-manager#44]
The interpolation result from avc_style_luma_interpolation_filter_vertical_ssse3_intrin is different with the one from avc_style_luma_interpolation_filter_vertical, which makes functions (i.e. avc_style_luma_interpolation_filter_pos{e, f, g, i, j, k, p, q, r}_ssse3) return wrong result.

**Comment by Cidana-Emma** [comment]
fixed, PR#568
