### ISSUE TITLE
[Test Framework] Setup a new environment for demo

### ISSUE THREAD

**Issue by Cidana-Emma** [Cidana-Developers/UnitTests-Task-manager#53]
- [x] set up a new environment for demo and external usage.
- [x] write "environment set up" documents 
- [x] write scripts for program building and environment setting

**Comment by Kenny-Cidana** [comment]
2 shell scripts have been created. 
  1. build.sh is in charge of component docker image building and uploading them to docker hub.
  2. launch.sh is in charge of fetching newest component docker images from docker hub and launch all of them one by one

**Comment by Kenny-Cidana** [comment]
deploy awcy media files via ftp

**Comment by Cidana-Emma** [comment]
Closed
