### ISSUE TITLE
[Test Framework] Simple log and full log cannot output completely on Web page

### ISSUE THREAD

**Issue by Cidana-Emma** [Cidana-Developers/UnitTests-Task-manager#56]

**Comment by Kenny-Cidana** [comment]
please assign to web UI engineer

**Comment by Cidana-Emma** [comment]
> please assign to web UI engineer

This issue has been reported to Web UI engineer, will change the assignee.

**Comment by Cidana-Emma** [comment]
fixed, so close this issue
