### ISSUE TITLE
[Test Framework] Add commit message in build info

### ISSUE THREAD

**Issue by Cidana-Emma** [Cidana-Developers/UnitTests-Task-manager#59]

**Comment by Kenny-Cidana** [comment]
Supported in API server side

**Comment by Kenny-Cidana** [comment]
@FochQu, please add new argument `commit_msg` in AddJobBuild API, just like what `commit` did

**Comment by FochQu** [comment]
Finish adding new api commit_msg in 3 tests

**Comment by Cidana-Emma** [comment]
Closed
