### ISSUE TITLE
[SVT-AV1 UnitTests] Investigate End2End test failures

### ISSUE THREAD

**Issue by Cidana-Emma** [Cidana-Developers/UnitTests-Task-manager#74]
PR#969 for reference:

[  FAILED  ] 68 tests, listed below:
[  FAILED  ] SvtAv1/CrashDeathTest.NotCrashTest/EncModeTest0, where GetParam() = EncModeTest0: EncoderMode=0, 
[  FAILED  ] SvtAv1/CrashDeathTest.NotCrashTest/EncModeTest1, where GetParam() = EncModeTest1: EncoderMode=1, 
[  FAILED  ] SvtAv1/CrashDeathTest.NotCrashTest/EncModeTest2, where GetParam() = EncModeTest2: EncoderMode=2, 
[  FAILED  ] SvtAv1/CrashDeathTest.NotCrashTest/EncModeTest3, where GetParam() = EncModeTest3: EncoderMode=3, 
[  FAILED  ] SvtAv1/CrashDeathTest.NotCrashTest/EncModeTest4, where GetParam() = EncModeTest4: EncoderMode=4, 
[  FAILED  ] SvtAv1/CrashDeathTest.NotCrashTest/EncModeTest5, where GetParam() = EncModeTest5: EncoderMode=5, 
[  FAILED  ] SvtAv1/CrashDeathTest.NotCrashTest/EncModeTest6, where GetParam() = EncModeTest6: EncoderMode=6, 
[  FAILED  ] SvtAv1/CrashDeathTest.NotCrashTest/EncModeTest7, where GetParam() = EncModeTest7: EncoderMode=7, 
[  FAILED  ] SvtAv1/CrashDeathTest.NotCrashTest/EncModeTest8, where GetParam() = EncModeTest8: EncoderMode=8, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/EncModeTest1, where GetParam() = EncModeTest1: EncoderMode=0, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/EncModeTest2, where GetParam() = EncModeTest2: EncoderMode=3, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/EncModeTest3, where GetParam() = EncModeTest3: EncoderMode=5, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/EncModeTest4, where GetParam() = EncModeTest4: EncoderMode=8, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/IntraPeriodTest1, where GetParam() = IntraPeriodTest1: IntraPeriod=-1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/IntraPeriodTest2, where GetParam() = IntraPeriodTest2: IntraPeriod=10, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/QpTest1, where GetParam() = QpTest1: QP=0, RateControlMode=0, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/QpTest2, where GetParam() = QpTest2: QP=10, RateControlMode=0, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/QpTest3, where GetParam() = QpTest3: QP=20, RateControlMode=0, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/QpTest4, where GetParam() = QpTest4: QP=32, RateControlMode=0, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/QpTest5, where GetParam() = QpTest5: QP=44, RateControlMode=0, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/QpTest6, where GetParam() = QpTest6: QP=63, RateControlMode=0, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/DlfTest1, where GetParam() = DlfTest1: LoopFilterDisable=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/FilmGrainTest1, where GetParam() = FilmGrainTest1: FilmGrain=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/ConstrainIntraTest1, where GetParam() = ConstrainIntraTest1: ConstrainedIntra=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/RateControlTest1, where GetParam() = RateControlTest1: RateControlMode=2, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/RateControlTest2, where GetParam() = RateControlTest2: RateControlMode=3, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/SCDTest1, where GetParam() = SCDTest1: SceneChangeDetection=0, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/LookAheadTest, where GetParam() = LookAheadTest: IntraPeriod=4, LookAheadDistance=6, RateControlMode=0, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/ScreenToolTest1, where GetParam() = ScreenToolTest1: ScreenContentMode=0, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/ScreenToolTest2, where GetParam() = ScreenToolTest2: EncoderMode=1, ScreenContentMode=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/AdapQTest1, where GetParam() = AdapQTest1: AdaptiveQuantization=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/AltrefTest1, where GetParam() = AltrefTest1: EnableAltRefs=0, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/TileTest1, where GetParam() = TileTest1: TileRow=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/TileTest2, where GetParam() = TileTest2: TileCol=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/TileTest3, where GetParam() = TileTest3: TileCol=1, TileRow=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/SpeedControlTest1, where GetParam() = SpeedControlTest1: speed_control_flag=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/IncompleteSbTest1, where GetParam() = IncompleteSbTest1: MaxQpAllowed=40, RateControlMode=2, TargetBitRate=100000, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/IncompleteSbTest2, where GetParam() = IncompleteSbTest2: MixQpAllowed=10, RateControlMode=2, TargetBitRate=1000000, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/PaletteModeTest1, where GetParam() = PaletteModeTest1: EncoderMode=1, PaletteMode=1, ScreenContentMode=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/PaletteModeTest2, where GetParam() = PaletteModeTest2: EncoderMode=1, PaletteMode=2, ScreenContentMode=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/PaletteModeTest3, where GetParam() = PaletteModeTest3: EncoderMode=1, PaletteMode=3, ScreenContentMode=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/PaletteModeTest4, where GetParam() = PaletteModeTest4: EncoderMode=1, PaletteMode=4, ScreenContentMode=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/PaletteModeTest5, where GetParam() = PaletteModeTest5: EncoderMode=1, PaletteMode=5, ScreenContentMode=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/PaletteModeTest6, where GetParam() = PaletteModeTest6: EncoderMode=1, PaletteMode=6, ScreenContentMode=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/PaletteModeTest7, where GetParam() = PaletteModeTest7: EncoderMode=1, PaletteMode=0, ScreenContentMode=1, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/DummySrcTest1, where GetParam() = DummySrcTest1: EncoderMode=8, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/DummySrcTest2, where GetParam() = DummySrcTest2: EncoderMode=8, Profile=2, 
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/DummySrcTest3, where GetParam() = DummySrcTest3: EncoderMode=8, Profile=1, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/IntraPeriodTest1, where GetParam() = IntraPeriodTest1: IntraPeriod=3, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/QpTest1, where GetParam() = QpTest1: QP=20, RateControlMode=0, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/QpTest2, where GetParam() = QpTest2: QP=32, RateControlMode=0, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/QpTest3, where GetParam() = QpTest3: QP=44, RateControlMode=0, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/RcTest1, where GetParam() = RcTest1: RateControlMode=2, TargetBitRate=1000000, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/RcTest2, where GetParam() = RcTest2: RateControlMode=2, TargetBitRate=750000, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/RcTest3, where GetParam() = RcTest3: RateControlMode=2, TargetBitRate=500000, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/RcTest4, where GetParam() = RcTest4: RateControlMode=3, TargetBitRate=1000000, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/RcTest5, where GetParam() = RcTest5: RateControlMode=3, TargetBitRate=750000, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/RcTest6, where GetParam() = RcTest6: RateControlMode=3, TargetBitRate=500000, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/RcQpTest1, where GetParam() = RcQpTest1: MinQpAllowed=20, RateControlMode=2, TargetBitRate=1000000, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/RcQpTest2, where GetParam() = RcQpTest2: MaxQpAllowed=50, RateControlMode=2, TargetBitRate=500000, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/RcQpTest3, where GetParam() = RcQpTest3: MaxQpAllowed=50, MinQpAllowed=20, RateControlMode=2, TargetBitRate=750000, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/RcQpTest4, where GetParam() = RcQpTest4: MinQpAllowed=20, RateControlMode=3, TargetBitRate=1000000, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/RcQpTest5, where GetParam() = RcQpTest5: MaxQpAllowed=50, RateControlMode=3, TargetBitRate=500000, 
[  FAILED  ] SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/RcQpTest6, where GetParam() = RcQpTest6: MaxQpAllowed=50, MinQpAllowed=20, RateControlMode=3, TargetBitRate=750000, 
[  FAILED  ] TILETEST/TileIndependenceTest.TileTest/TileTest1, where GetParam() = TileTest1: TileCol=0, TileRow=0, 
[  FAILED  ] TILETEST/TileIndependenceTest.TileTest/TileTest2, where GetParam() = TileTest2: TileCol=0, TileRow=1, 
[  FAILED  ] TILETEST/TileIndependenceTest.TileTest/TileTest3, where GetParam() = TileTest3: TileCol=1, TileRow=0, 
[  FAILED  ] TILETEST/TileIndependenceTest.TileTest/TileTest4, where GetParam() = TileTest4: TileCol=1, TileRow=1,

**Comment by Cidana-Emma** [comment]
PR#992: Fix all tests from SvtAv1E2ETests. 
Please help to verify if this PR can fix all the E2E test failures. Thank you.

**Comment by edmond-zhu** [comment]
Verified PR #992, all e2e test passed list:
~~~
16:00:05 [==========] 66 tests from 4 test cases ran. (2003779 ms total)
16:00:05 [  PASSED  ] 66 tests.
~~~

But found one crash:
~~~
Fatal Error on running test case RcTest6: RateControlMode=1, TargetBitRate=500000, test vector: kirland_640_480_30.yuv
[  DEATH   ] *** Error in `./Bin/Release/SvtAv1E2ETests': double free or corruption (out): 0x00007fcca400fb20 ***
~~~

For more details, please check for [full log](http://jenkins.cidanash.com:8082/job/SVTAV1-Linux-GCC-Dry-Run-Test/143/consoleFull)

**Comment by Cidana-Emma** [comment]
Closed
