### ISSUE TITLE
[SVT-AV1 UnitTests] Investigate Deblocking test coverage

### ISSUE THREAD

**Issue by Cidana-Emma** [Cidana-Developers/UnitTests-Task-manager#75]
Deblocking unit test coverage decrease to 11%, need to investigate what's the issue happened in it.

**Comment by edmond-zhu** [comment]
There are some test cases missing in first version of DeblockTest.cc

New test cases added in PR: https://github.com/Cidana-Developers/SVT-AV1/pull/122

**Comment by Cidana-Emma** [comment]
Issued PR#1042, so closed
