### ISSUE TITLE
[SVT-AV1 UnitTests] Investigation of Rate Control Failure Test Cases

### ISSUE THREAD

**Issue by edmond-zhu** [Cidana-Developers/UnitTests-Task-manager#84]
Failure test cases founded in [PR1044](https://github.com/OpenVisualCloud/SVT-AV1/runs/444877473) and [PR1045](https://github.com/OpenVisualCloud/SVT-AV1/runs/445233347)

The failure test cases are:
SvtAv1/CodingOptionTest.CheckEncOptionsUsingBitstream/RcTest2 and SvtAv1/ConformanceDeathTest.DefaultSettingTest/RateControlTest1

Verify and investigate the issues.

**Comment by edmond-zhu** [comment]
After test more than 10 thousands times of running rate control test cases, It is re-produced 4 times by following process:
~~~
1.	Runs SvtAv1EncApp to encode YUV to IVF file and collects reconstruction frame
2.	Runs SvtAv1DecApp to decode IVF (generated in #1) to YUV output
3.	Calculate MD5 checksum of reconstruction frame (generated in #1) and decoded YUV (generated in #2)
4.	Compare the checksums
~~~
This issue is not related with Cidana end to end test framework, since it is based on SvtAv1EncApp and SvtAv1DecApp.

I uploaded the test script and test results to [file-server](\\fileserver\Public\Employees\Edmond\AV1\rctest_results)

How to run test script:
~~~
1.	Clone SVT-AV1 source code from GitHub
2.	Copy run_rctest.sh to the root of source directory
3.	Run test with following format: run_rctest.sh <repeat_num>
4.	Only failed test cases will keep the YUV files and logs after testing
~~~

And there are two different phenomena:
1)	Decoder reports errors in log: Invalid length in read_golomb (in dec_log_rc6_170.txt)
2)	Decoder not reports error, but the MD5 checksum of recon and decoded YUV files are different.
After manually checked with dav1d, the matrix is as below:

Test Case | MD5 Checksum | Decode Log | dav1d Log
-- | -- | -- | --
rc4_127 | different | no error | error
rc4_347 | different | no error | no error
rc6_170 | different | error | error
rc6_196 | different | no error | no error

There might be two different issues in encoder or decoder.

**Comment by Cidana-Emma** [comment]
Feedback to Netflix, so close it.
